### PR TITLE
Fix configure_networks

### PR DESCRIPTION
**Pull request by ailispaw**
- Use systemd-networkd

### CODE REVIEW

**Comment by frapposelli** [comment]
Thanks! can you please modify the test unit accordingly?

**Comment by ailispaw** [comment]
@frapposelli 
I'm trying to modify the test unit, but it will take some time because I'm not familiar with rspec.
I cat not test inside the networks block yet due to empty interfaces on testing.

**Comment by ailispaw** [comment]
I modified the test units.
Please advise me if you have any concern about it.
Thanks.

**Comment by frapposelli** [comment]
Looking good! thanks!

**Comment by frapposelli** [comment]
Can you please squash your commits?

**Comment by ailispaw** [comment]
Sure

**Comment by ailispaw** [comment]
Done

**Comment by frapposelli** [comment]
Perfect! thank you!

**Pull request merged**
